### ISSUE TITLE
Zverejnenie anonyzovanych ziadosti

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#174]
- [x] Identifikovat typy suborov: #176, #177
- [x] Znormalizovat prilohy do PDF: #173, #178, #179, #181, #180, #182, #183
- [x] OCRkovat znormalizovane prihlohy do ODT: #184 
- [x] V ODT nahradit meno/ulicu uzivatela "xxxxxxxx": #185 
- [x] Mozno skonvertovat sanitizovane ODT naspat do PDF: #186
- [x] Verejna obrazovka s detailom ziadosti + sanitizovanie v textoch v ziadosti: #207, #212
- [x] Sitemap s verejnymi ziadostami: #208
- [x] Vyrejna obrazovka so zoznamom ziadosti: #210
- [x] Vyhladavanie vo verejnych ziadostiach (cez google): #209

Presunute do dalsieho milestone:
- Nastavenie: Vypnutie anonymizovania: #231
- Nastavenie: Custom anonymizovane stringy: #232
- Nastavenie: Po akej dobe od uzavretia ziadosti ju zverejnit: #233

Zatial nerobime, lebo je to moc komplikovane:
- Rucne anonymizovanie (ci uz textbox kde sa bude dat mazat, alebo GUI na vyciernovanie v pdf)
