### ISSUE TITLE
Nastylovanie textovych obrazoviek

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#337]
Kazdy bod (checkbox) rob pls v samostatnom PR.

- [x] Nastyluj prave podmenu ako je popisane v https://github.com/martinmacko47/chcemvediet/issues/67#issuecomment-170110978. Pricom tie sede sipky, co su v tom menu vyhodime. Pozor su tam dva rezy. Prvy na desktope, vtedy je menu vpravo. Druhy na mobile, vtedy je menu na spodku pod textom. Nastylovanie ma byt responsivne, tj. ked menis velkost viewportu, ma sa automaticky prisposobovat.
   - [x] Pridat komponent pre podmenu do styleguide. Bud do sekcie "Components" alebo do samostatnej sekcie.
- [x] Nastyluj obsah obrazovky [FAQ](https://www.chcemvediet.sk/sk/faq/) ako je popisane v https://github.com/martinmacko47/chcemvediet/issues/67#issuecomment-170110978. Jednotlive otazky maju byt expandovatelne. To by malo ist spravit standardne bootstrapovymi nastrojmi.
- Nastyluj obsah obrazoviek [Ochrana osobných údajov](https://www.chcemvediet.sk/sk/ochrana-osobnych-udajov/) a [Podmienky používania](https://www.chcemvediet.sk/sk/podmienky-pouzivania/) (suvisi s https://github.com/martinmacko47/chcemvediet/issues/54#issuecomment-172300245):
   - [x] Podnadpisy, ktore su teraz kapitalkami, zmen na skutocne podnadpisy bez pouzitia kapitalok. 
   - [x] Kde sa v texte spomina nejaky zakon / paragraf, sprav z neho linku na dany zakon / paragraf na https://www.slov-lex.sk/domov otvaranu v novom tabe
   - [x] Kazdemu odstavcu v texte daj anchor id, aby sa dali robit odkazy medzi odstavcami. A vsade kde sa text odvolava na iny odstavec, sprav tu odvolavku ako link na prislusny anchor.
   - [x] Kde sa spomina nejaka webstranka, odkaz na nieco externe alebo interne na nasom webe, sprav z toho linku. Externe linky sa maju otvarat v novom tabe, interne v aktualnom tabe.
   - [x] Cisla na zaciatku odstavcov daj boldom ~a modrou farbou~
- [x] Sekciu "Zdroje" na obrazovkach [Právo na informácie](https://www.chcemvediet.sk/sk/pravne-predpisy/) a [Načo infozákon](https://www.chcemvediet.sk/sk/pripadove-studie/) nastyluj ako je popisane v https://github.com/martinmacko47/chcemvediet/issues/68#issuecomment-170118454
- [x] Na obrazovke [Podporte nás](https://www.chcemvediet.sk/sk/podporte-nas/) uprav stlpce, nech nie je vsetok text v jednom stlpci.
   - V sekcii "2% z daní" daj odstavec "fyzická osoba" do praveho stlpca.
   - V sekcii "Aké sú naše výsledky?" daj "Výročné správy" do praveho stlpca.
   - Pozor aby na mobile sa to zalomilo spravne naspat do jedneho stlpca.
- [x] Skontrolovat, ze sekcia [Podávanie žiadostí](https://www.chcemvediet.sk/sk/podavanie-ziadosti/) naplnena textom v #335 je tiez nastylovana rozumne, analogicky ako ostatne obrazovky s textami
- [x] Prejdi celu codebase / vsetky obrazovky, ci niekde nieco tiez netreba analogicky upravit, ako sme upravovali v predoslych bodoch.
